name: Auto Deploy Satellite Sites

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行
  workflow_dispatch:      # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests google-auth-oauthlib google-auth-httplib2 google-api-python-client
    
    - name: Run deployment script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GDRIVE_SERVICE_ACCOUNT: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
        NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |
        python auto_deploy.py
