name: Auto Deploy

on:
push:
branches:
- main
schedule:
- cron: '0 0 * * *' # 每天 UTC 时间 00:00 运行一次
workflow_dispatch: # 添加这一行，允许手动触发

jobs:
deploy:
runs-on: ubuntu-latest
permissions:
contents: read

steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.10'

  - name: Install dependencies
    run: |
      pip install google-api-python-client google-auth requests vercel netlify-cli

  - name: Run deployment script
    env:
      GDRIVE_SERVICE_ACCOUNT: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
      GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
    run: |
      python auto_deploy.py
