name: Auto Update HTML from Google Drive

on:
  workflow_dispatch:       # 手动触发
  schedule:
    - cron: "0 */6 * * *"  # 每 6 小时自动运行一次

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib requests

      - name: Run auto_deploy.py
        env:
          # Google Drive
          GDRIVE_SERVICE_ACCOUNT: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}

          # GitHub
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Netlify
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

          # Vercel
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

        run: python auto_deploy.py
